truths = [
    "Have you ever lied to your best friend?",
    "What's your biggest fear?",
    "What's the most embarrassing thing that's happened to you?",
    "Have you ever cheated on a test or exam?",
    "What's a secret you've never told anyone?",
    "Have you ever stolen something?",
    "What's your guilty pleasure?",
    "Have you ever lied to your best friend?",
    "What's your biggest fear?",
    "What's the most embarrassing thing that's happened to you?",
    "Have you ever cheated on a test or exam?",
    "What's a secret you've never told anyone?",
    "Have you ever stolen something?",
    "What's your guilty pleasure?",
    "Have you ever pretended to like a gift you didn't like?",
    "What's the weirdest food you've ever eaten?",
    "Have you ever been in a fight?",
    "What's your most irrational fear?",
    "Have you ever had a crush on a teacher?",
    "What's the last lie you told?",
    "Have you ever been caught in a lie?",
    "What's your most embarrassing childhood memory?",
    "Have you ever cheated in a relationship?",
    "What's the most embarrassing thing in your internet search history?",
    "Have you ever been on a blind date?",
    "What's your most prized possession?",
    "Have you ever been in love?",
    "What's the most romantic thing you've ever done for someone?",
    "Have you ever had a one-night stand?",
    "What's your biggest regret?",
    "Have you ever had a secret crush on someone?",
    "What's the worst thing you've ever done to someone?",
    "Have you ever cheated at a game?",
    "What's the most embarrassing thing you've done while drunk?",
    "Have you ever broken the law?",
    "What's a habit you're trying to break?",
    "Have you ever lied on your resume?",
    "What's the most trouble you've ever been in with your parents?",
    "Have you ever skipped school or work without an excuse?",
    "What's the most childish thing you still do as an adult?",
    "Have you ever had a fake ID?",
    "What's the most childish TV show or movie you still enjoy?",
    "Have you ever regretted breaking up with someone?",
    "What's the most money you've spent on something frivolous?",
    "Have you ever lied to get out of trouble?",
    "What's the biggest lie you've ever told your parents?",
    "Have you ever snooped through someone else's things?",
    "What's the most expensive thing you've stolen?",
    "Have you ever gone through someone's phone without their permission?",
    "What's the most embarrassing text message you've sent by mistake?",
    "Have you ever had a crush on a coworker?",
    "What's the most embarrassing thing you've said in a job interview?",
    "Have you ever pretended to be sick to get out of a social event?",
    "What's the most embarrassing thing you've posted on social media?",
    "Have you ever cheated at a sport?",
    "What's the worst date you've ever been on?",
    "Have you ever ghosted someone after a date?",
    "What's the most embarrassing thing you've worn in public?",
    "Have you ever lied about your age?",
    "What's the most embarrassing thing you've done in front of your crush?",
    "Have you ever had a crush on a friend's partner?",
    "What's the most embarrassing nickname you've been called?",
    "Have you ever lied to get a job?",
    "What's the most embarrassing thing you've done at a party?",
    "Have you ever had a secret online persona?",
    "What's the most embarrassing thing you've said to your boss?",
    "Have you ever lied to avoid going to a family event?",
    "What's the most embarrassing thing you've done in a group photo?",
    "Have you ever cheated at a board game?",
    "What's the worst thing you've ever done to someone?",
    "Have you ever lied to a significant other about where you were?",
    "What's the most embarrassing thing you've done in a store?",
    "Have you ever cheated on a board game?",
    "What's the most embarrassing thing you've done on a video call?",
    "Have you ever lied to a significant other about your past?",
    "What's the most embarrassing thing in your internet search history?",
    "Have you ever had a secret crush on someone?",
    "What's the last lie you told?",
    "Have you ever cheated on a test or exam?",
    "What's your most embarrassing childhood memory?",
    "Have you ever cheated at a competition?",
    "What's the most embarrassing thing you've said to your partner during a fight?",
    "Have you ever been in a fight?",
    "What's the most embarrassing thing you've done while drunk?",
    "Have you ever broken the law?",
    "What's the most embarrassing thing you've done at a wedding?",
    "Have you ever had a crush on a teacher?",
    "What's your most irrational fear?",
    "Have you ever had a fake ID?",
    "What's the most expensive thing you've stolen?",
    "Have you ever pretended to like a gift you didn't like?",
    "What's the most embarrassing thing you've done on a date?",
    "Have you ever stolen something?",
    "What's your guilty pleasure?",
    "Have you ever been in love?",
    "What's the most embarrassing thing you've posted on social media?",
    "Have you ever had a one-night stand?",
    "What's your most prized possession?",
    "Have you ever been caught in a lie?",
    "What's your biggest fear?",
    "Have you ever cheated at a video game?",
    "What's the weirdest food you've ever eaten?",
    "Have you ever pretended to be sick to get out of a social event?",
    "What's the most embarrassing thing you've done in a restaurant?",
    "Have you ever lied about your age to get into a club?",
    "What's the most childish thing you still do as an adult?",
    "Have you ever regretted breaking up with someone?",
    "What's the most money you've spent on something frivolous?",
    "Have you ever had a secret online persona?",
    "What's the most embarrassing thing you've done at a family gathering?",
    "Have you ever cheated in a relationship?",
    "What's the most childish TV show or movie you still enjoy?",
    "Have you ever cheated at a game?",
    "What's the most embarrassing thing you've done at a library?",
    "Have you ever had a crush on a coworker?",
    "What's the most embarrassing thing you've said to your boss?",
    "Have you ever been on a blind date?",
    "What's the most expensive thing you've stolen?",
    "Have you ever gone through someone's phone without their permission?",
    "What's the most embarrassing text message you've sent by mistake?",
    "Have you ever cheated on a test?",
    "What's the most embarrassing thing you've done at a job interview?",
    "Have you ever snooped through someone else's things?",
    "What's the biggest lie you've ever told your parents?",
    "Have you ever lied to get a job?",
    "What's the most trouble you've ever been in with your parents?",
    "Have you ever skipped school or work without an excuse?",
    "What's a habit you're trying to break?",
    "Have you ever broken the law?",
    "What's the most embarrassing thing you've done in a public restroom?",
    "Have you ever been caught in a lie?",
    "What's the most embarrassing thing you've done in a classroom?",
    "Have you ever lied on your resume?",
    "What's the most embarrassing thing you've said to your partner during a fight?",
    "Have you ever cheated at a video game?",
    "What's the most embarrassing thing you've done on a video call?",
    "Have you ever had a crush on a teacher?",
    "What's your most irrational fear?",
    "Have you ever been in a fight?",
    "What's the last lie you told?",
    "Have you ever had a secret crush on someone?",
    "What's the most embarrassing thing in your internet search history?",
    "Have you ever stolen something?",
    "What's your guilty pleasure?",
    "Have you ever pretended to like a gift you didn't like?",
    "What's the weirdest food you've ever eaten?",
    "Have you ever cheated on a test or exam?",
    "What's your biggest fear?",
    "Have you ever lied to your best friend?",
    "What's the most embarrassing thing that's happened to you?",
    "Have you ever had a fake ID?",
    "What's your most prized possession?",
    "Have you ever been in love?",
    "What's the most romantic thing you've ever done for someone?",
    "Have you ever had a one-night stand?",
    "What's your biggest regret?",
    "Have you ever had a secret online persona?",
    "What's the most expensive thing you've spent on something frivolous?",
    "Have you ever lied to get out of trouble?",
    "What's the most embarrassing thing you've done at a party?",
    "Have you ever cheated at a sport?",
    "What's the worst date you've ever been on?",
    "Have you ever ghosted someone after a date?",
    "What's the most embarrassing thing you've worn in public?",
    "Have you ever lied about your age?",
    "What's the most childish thing you still do as an adult?",
    "Have you ever had a secret crush on someone?",
    "What's the most embarrassing nickname you've been called?",
    "Have you ever lied to get a job?",
    "What's the most embarrassing thing you've said in a job interview?",
    "Have you ever stolen something?",
    "What's the most embarrassing thing you've done while drunk?",
    "Have you ever been caught in a lie?",
    "What's your most embarrassing childhood memory?",
    "Have you ever cheated in a relationship?",
    "What's the most embarrassing thing in your internet search history?",
    "Have you ever been on a blind date?",
    "What's the last lie you told?",
    "Have you ever had a crush on a teacher?",
    "What's the most trouble you've ever been in with your parents?",
    "Have you ever cheated on a board game?",
    "What's your most irrational fear?",
    "Have you ever been in a fight?",
    "What's the most embarrassing thing you've done in front of your crush?",
    "Have you ever had a fake ID?",
    "What's your most prized possession?",
    "Have you ever pretended to like a gift you didn't like?",
    "What's the weirdest food you've ever eaten?",
    "Have you ever cheated at a competition?",
    "What's the most embarrassing thing you've said to your partner during a fight?",
    "Have you ever cheated at a card game?",
    "What's the most embarrassing thing you've done on a video call?",
    "Have you ever gone through someone's phone without their permission?",
    "What's the most embarrassing thing you've done on a date?",
]

dares = [
    "Do a funny dance and record it.",
    "Eat a spoonful of hot sauce or a chili pepper.",
    "Sing a song in a funny voice.",
    "Call a random contact from your phone and sing 'Happy Birthday' to them.",
    "Put an ice cube down your pants and keep it there until it melts.",
    "Speak in an accent of your choice for the next three rounds.",
    "Make up a short rap and perform it for everyone.",
    "Wear socks on your hands for the next three rounds.",
    "Let someone draw a funny face on your cheek with a marker.",
    "Send a text message to your crush saying you like them (and you can't take it back).",
    "Wear your clothes backward for the next two rounds.",
    "Let someone give you a makeover with makeup or face paint.",
    "Call a pizza place and order a pizza with toppings chosen by the group.",
    "Dress up in a costume of the group's choice for the next two rounds.",
    "Put on a blindfold and eat a mystery food item chosen by the group.",
    "Post an embarrassing photo of yourself on social media.",
    "Give a 2-minute speech about a random topic chosen by the group.",
    "Take a spoonful of peanut butter without water.",
    "Speak in pig Latin for the next three rounds.",
    "Wear a piece of clothing inside out for the next two rounds.",
    "Do a handstand against a wall for 30 seconds.",
    "Eat a spoonful of mustard or mayonnaise.",
    "Let someone tie your shoelaces together, and try to walk in them.",
    "Wear a 'kick me' sign on your back for the next two rounds.",
    "Put on a blindfold and try to draw a picture chosen by the group.",
    "Talk in rhymes for the next three rounds.",
    "Eat a spoonful of ketchup or salsa.",
    "Give a piggyback ride to someone for one round.",
    "Wear a funny hat for the next two rounds.",
    "Recite the alphabet backward without any mistakes.",
    "Put on a blindfold and try to guess what food you're tasting (chosen by the group).",
    "Let someone write a funny message on your forehead with a marker.",
    "Talk like a robot for the next three rounds.",
    "Wear your shoes on your hands for one round.",
    "Recite a tongue twister without making any mistakes.",
    "Call a random contact from your phone and tell them a made-up story.",
    "Eat a spoonful of pickles or olives.",
    "Wear a mustache made of paper for the next two rounds.",
    "Do a handstand against a wall for 45 seconds.",
    "Tell a joke and make everyone laugh.",
    "Act like a mime for the next two rounds.",
    "Put on a blindfold and touch a mystery item chosen by the group.",
    "Wear a silly wig for the next three rounds.",
    "Recite a poem (can be a short one) from memory.",
    "Take a spoonful of a spicy sauce or salsa.",
    "Let someone give you a new hairstyle using hair gel or styling products.",
    "Talk with your tongue sticking out for one round.",
    "Wear a pair of underwear on top of your pants for the next two rounds.",
    "Do a handstand against a wall for 1 minute.",
    "Recite a tongue twister without making any mistakes.",
    "Let someone draw a funny mustache on your face with a marker.",
    "Wear a pair of funny glasses for the next three rounds.",
    "Dance like nobody's watching for one round.",
    "Call a random contact from your phone and tell them you won the lottery (and you can't take it back).",
    "Wear a sock puppet on one hand for the next two rounds.",
]


import random
def randomnumber():
    ranum = random.randint(0,82914792481989124012)


owner1 = ".wuid"
owner2 = "papiertanne"
owner3 = "._0kyra0_."
owner4 = "llit_im_internet"
owner5 = "messitheking"
owner6 = "pepeyt"